### ISSUE TITLE
Deployed Portfolio Project

### ISSUE THREAD

**Issue by Fayob** [Fayob/portfolio-setup-project#6]
https://fayob.github.io/portfolio-setup-project/

**Comment by zhadier** [comment]
# Hi @Fayob  👋 

Good job so far! 🌤️ 
There are some issues that you still need to work on to go to the next project but you are almost there! 🍓 

<img src="https://media4.giphy.com/media/5wWf7GR2nhgamhRnEuA/giphy.gif"/>

## Highlights
✔️Great job on the deployment


## Required Changes ♻️

- [ ] Kindly ensure that you add the deployment link under the `Live Demo` section of your ReadMe as specified in the Microverse ReadMe template. It'll make it much easier for people with lacking technical experience to access your website

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question @zhadier so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Fayob** [comment]
Please I don't understand and know where to add the link in the live demo, is it on my ReadMe file ?

**Comment by zhadier** [comment]
> Please I don't understand and know where to add the link in the live demo, is it on my ReadMe file ?

- Yes it should be in your ReadMe file under a heading `Live Demo`

**Comment by Fayob** [comment]
Alright, Thank you very much

**Comment by 1GORDON** [comment]
# Status: APPROVED 🟢 

Hi @zhadier ✋

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:


## Optional suggestions

- [ ] Kindly use a Pull request instead of an issue to submit your work for review

##### _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

##### Cheers and Happy coding!:clap::clap::clap:
##### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
